path: /exact/path/to/root/dir # dataset root dir
train: /exact/path/to/root/dir/training  # train images 
val: /exact/path/to/root/dir/val # val images 

# Classes
names:
  0: tags
  1: tags

  #input the tags name here i.e if ur training dogs and cats, then check with your annotations and match them here.